### ISSUE TITLE
Starships 404s

### ISSUE THREAD

**Issue by freddyh** [Juriy/swapi#13]
https://swapi.dev/api/starships/1/ and https://swapi.dev/api/starships/4/ are returning 404s

**Comment by Juriy** [comment]
Generally speaking for APIs it is perfectly normal to have 404s for some IDs: clients should not rely that every ID in a sequence has an entity attached to it. Moreover most modern APIs discourage the use of numeric IDs (generating pseudorandom strings instead), which makes iteration impossible.
