### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by mfierro31** [Juriy/swapi#16]
Hello,

I've been using swapi.dev for a rather big project for a coding class I'm taking and now I'm getting an error whenever I try to make an API request to the site.  It says:

requests.exceptions.SSLError: HTTPSConnectionPool(host='swapi.dev', port=443): Max retries exceeded with url: /api/planets/1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)')))

I also clicked on the 'Not Secure' part of the URL window in Chrome when I visit swapi.dev (it's just showing a 'Connection Not Private' error page) and it says your 'Let's Encrypt' certificate expired on Saturday, October 10, 2020 at 9:06:41 PM Pacific Daylight Time.  

Can you please get it up and running again?  I'm relying heavily on the planets info for my project.  

Thanks!

**Comment by Deirdre18** [comment]
I also have had problem, was just about finished developing an app using this api and was working fine yesterday but this morning is totally gone. Can't view documentation even. Would also like for it to be back up and running.

**Comment by Deirdre18** [comment]
@mfierro31 there is another starwars api you might be interested in using, it uses Deno and Stvete. This is the website link and github repository. It's an alternative api on azure platform.

https://swapi-deno.azurewebsites.net/
https://github.com/rodolphocastro/deno-swapi

**Comment by mfierro31** [comment]
@Deirdre18 Ahh, interesting. If the info is all the same, that would be a great alternative. I'll check that one out. Thanks!

**Comment by frblazquez** [comment]
**Expired again today, 11th April 2021**

**Comment by Deirdre18** [comment]
@frblazquez - thanks for letting me know, I'm using the api in an app I'm developing, and it's still working despite the outdated certificate.

**Comment by Deirdre18** [comment]
@juriy, Hi Juriy, do you know if swapi api will be working again, as I'm using it for an app I've developed? Is there any other alternative? Thanks.

**Comment by frblazquez** [comment]
@Deirdre18 - It's currently working! Are you experiencing any issue? I used it yesterday without any problem. If the issue persist you can also use https://swapi.py4e.com/

Hope it helps!

**Comment by Deirdre18** [comment]
@frblazquez - many thanks. It is working now, but earlier thought it wasn't.
