### ISSUE TITLE
Http failure response for https://swapi.dev/api/films

### ISSUE THREAD

**Issue by Deirdre18** [Juriy/swapi#17]
Hi, I was greeted with this error this morning. API has been working good up until today. Seems a certificate error from what I can gather. Would really appreciate to have it working again. Thanks.

Error:-

message: "Http failure response for https://swapi.dev/api/films: 0 Unknown Error"
​name: "HttpErrorResponse"

**Comment by Juriy** [comment]
I apologising for any inconveniences caused by certs. The cert request process was misconfigured, hence the issues. Should work better now.
