### ISSUE TITLE
Links color

### ISSUE THREAD

**Issue by Ch1sKey** [Juriy/swapi#2]
![image](https://user-images.githubusercontent.com/20926428/80380172-dbfe1800-88a7-11ea-8a03-a8e1df977e81.png)

https://swapi.dev/api/people/

**Comment by Juriy** [comment]
Thanks for the report
![Screenshot 2021-06-17 at 00 43 38](https://user-images.githubusercontent.com/460586/122304233-2e175800-cf05-11eb-843e-96e6321186b3.png)
! Fixed.
