### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by yccgabby** [Juriy/swapi#22]
Expired on January 9th 2021

**Comment by emirotin** [comment]
Yeah, a bit unfortunate, I use it as an educational project for my students. Can I help with this problem somehow @Juriy?

**Comment by The24thDS** [comment]
I found this fork and it's still online https://swapi.py4e.com/

**Comment by tarasvladyka** [comment]
There's also one more www.swapi.tech, but it has a bit different structure of response . And the one which The24thDS proposes seems to be the most closer to what swapi.dev was.

**Comment by tarasvladyka** [comment]
There's also a workaround if you still want to use swapi.dev.
1. Open in new tab https://swapi.dev/api/people/
2. Just type `thisisunsafe`

Details about `thisisunsafe `-> https://dev.to/brettimus/this-is-unsafe-and-a-bad-idea-5ej4

**Comment by frblazquez** [comment]
**Expired again today, 11th April 2021**

**Comment by Juriy** [comment]
Got to automate the renewal :)
