### ISSUE TITLE
JSON-LD Support?

### ISSUE THREAD

**Issue by zwelz3** [Juriy/swapi#26]
The old swapi.co provided a data dump in RDF serializations (e.g. turtle), which allowed processing the data with SPARQL, etc.

The new API returns basic JSON with no (obvious) way to recover the JSON-LD context in order to expand the data. This breaks all linked-data usages.

Are there any plans to support JSON-LD type, host the context, or host the data as serialized RDF?

**Comment by Juriy** [comment]
That is a really strange bug: API format shouldn't have changed since there was literally no code changes until now. I'm not very familiar with JSON-LD, if you could give a bit more details about the format I'll be happy to check out what can be done.
