### ISSUE TITLE
add CORS support

### ISSUE THREAD

**Issue by ianstormtaylor** [Juriy/swapi#27]
I don't think CORS is enabled on this, which makes it impossible to request the API from Chrome? It looks like it was solved in the upstream repository: https://github.com/phalt/swapi/issues/60

**Comment by jessica-au** [comment]
I am also running into this issue when testing out this api.

**Comment by Juriy** [comment]
Could you double-check that please, for me it seems to be working fine. The command below simulates a pre-flight CORS request, and response contains correct headers that allow * (everything) origin:

```
curl -v --silent -H "Origin: http://example.com" \
  -H "Access-Control-Request-Method: GET" \
  -H "Access-Control-Request-Headers: X-Requested-With" \
  -X OPTIONS  \
  https://swapi.dev/api/ 2>&1| grep access-control-allow
```
Response:

```
< access-control-allow-headers: x-requested-with, content-type, accept, origin, authorization, x-csrftoken, user-agent, accept-encoding
< access-control-allow-methods: GET
**< access-control-allow-origin: ***
```
