### ISSUE TITLE
404 on documentation and about pages

### ISSUE THREAD

**Issue by nachtien** [Juriy/swapi#34]
I am currently receiving 404's on the documentation page.  I am clicking on the links from the home page. 

https://swapi.dev/documentation
https://swapi.dev/about

![image](https://user-images.githubusercontent.com/116726/122303342-030f1300-cec9-11eb-9d89-073431ee4de2.png)

**Comment by Juriy** [comment]
Thanks! Obviously a configuration issue, will likely to fix it tomorrow...

**Comment by Juriy** [comment]
All right, this was an unexpected side-effect, but fixed now. Thanks!
