### ISSUE TITLE
URLs in request body pointing to localhost:8001 instead swapi.dev

### ISSUE THREAD

**Issue by michaelcowansmsja** [Juriy/swapi#35]
Might be due to a recent update. But after making a request to the endpoint. 
URI values in the response body are pointing to localhost instead of the swapi.dev url.
Example: 

FROM
https://swapi.dev/api/planets/1/
TO
https://localhost:8001/api/planets/1/

**Comment by Juriy** [comment]
Thanks for heads up, all should be back to normal now.

**Comment by michaelcowansmsja** [comment]
Awesome. Thanks again for the API. Great project you have running here.
