### ISSUE TITLE
swapi.dev rate limited after one api call

### ISSUE THREAD

**Issue by kevindurb** [Juriy/swapi#36]
I havent made any api calls to swapi.dev in at least a couple weeks and this morning I made one api call (`https://swapi.dev/api/people/1`) and got 
```
HTTP 429 TOO MANY REQUESTS
Retry-After: 25924
Content-Type: application/json
Vary: Accept
Allow: GET, HEAD, OPTIONS

{
    "detail": "Request was throttled. Expected available in 25924 seconds."
}
```

**Comment by stevencribbs** [comment]
I am getting a similar experience.  I haven't used the API in quite a while; and, this morning I am getting the same 429 error with `{"detail":"Request was throttled. Expected available in 25463 seconds."}`.

**Comment by alexbeckwith** [comment]
Same here

**Comment by Juriy** [comment]
Fixed. Sorry for an inconvenience...
