### ISSUE TITLE
request with https://swapi.dev/api Redirect 301 to http://swapi.dev/api

### ISSUE THREAD

**Issue by davidfigueroar9** [Juriy/swapi#6]
![image](https://user-images.githubusercontent.com/9356341/83082258-46e27080-a059-11ea-9545-76d07a0f2589.png)

**Comment by marr** [comment]
This issue is preventing me from using the API in a browser context. Do you have plans to fix the redirect from https to http?

**Comment by robaxelsen** [comment]
Same issue here. Any update, @Juriy?

**Comment by Juriy** [comment]
Sorry for a significant delay with a response. I'm on it now.

**Comment by Juriy** [comment]
Fixed
