### ISSUE TITLE
Aren't there at least 9 movies?

### ISSUE THREAD

**Issue by aaaronic** [Juriy/swapi#8]
It seems like the latest trilogy and the extended universe movies aren't in the data set.

The Mandalorian, the Clone Wars, and Rebels are all considered cannon at this point now too. Has a decision been made not to include anything post-Disney acquisition (or are PRs welcome)?

**Comment by alexmojaki** [comment]
And if the API doesn't want to include the sequels, at least remove this from the home page:

> From all SEVEN Star Wars films

> Now with The Force Awakens data!

**Comment by Juriy** [comment]
The data hasn't been updated for some time. Adding more titles and entities are in the scope but they are lower priority than some of the identified bugfixes.
